# Generated by Django 2.1.3 on 2018-12-20 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20181220_1704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='blogs',
            new_name='blog',
        ),
    ]
